# Generated by Django 2.0.4 on 2018-06-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('abstract', models.TextField()),
                ('author', models.CharField(max_length=10)),
                ('publisher', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='abstract',
            name='keywords',
            field=models.ManyToManyField(to='ir.Keyword'),
        ),
    ]
